apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agentforge
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/subhankar720/helmsman-fleet.git
    targetRevision: main
    path: apps/agentforge
    directory:
      exclude: "argocd-application.yaml"
  destination:
    name: helmsman-onprem
    namespace: agentforge
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    # Kyverno policies target namespaces with this label
    managedNamespaceMetadata:
      labels:
        helmsman.dev/managed: "true"
