apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: vault
  labels:
    app: vault
    app.kubernetes.io/managed-by: helmsman
spec:
  selector:
    app: vault
  ports:
    - name: http
      port: 8200
      targetPort: 8200
      protocol: TCP
      nodePort: 30082
  type: NodePort
