apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-access-rbac
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/subhankar720/helmsman-fleet.git
    targetRevision: main
    path: platform/access-rbac
    directory:
      exclude: "argocd-application.yaml"
  destination:
    name: helmsman-onprem
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
