apiVersion: v1
kind: Service
metadata:
  name: loki-nodeport
  namespace: monitoring
  labels:
    app: loki-nodeport
    app.kubernetes.io/managed-by: helmsman
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: single-binary
  ports:
    - name: http
      port: 3100
      targetPort: 3100
      nodePort: 30031
      protocol: TCP
