apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-fluent-bit-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "golden-path-chart.labels" . | nindent 4 }}
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush             5
        Daemon            Off
        Log_Level         info
        Parsers_File      parsers.conf

    [INPUT]
        Name              tail
        Path              /var/log/app/app.log
        Tag               app.{{ .Values.appName }}
        Parser            json
        Refresh_Interval  5
        Skip_Empty_Lines  On

    [OUTPUT]
        Name              stdout
        Match             *
        Format            json_lines

  parsers.conf: |
    [PARSER]
        Name          json
        Format        json
        Time_Key      timestamp
        Time_Format   %Y-%m-%dT%H:%M:%SZ
