{{- if .Values.oidc.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.appName }}-oidc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "golden-path-chart.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ .Values.appName }}-oidc
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: apps/{{ .Values.appName }}/oidc
        property: client-id
    - secretKey: client-secret
      remoteRef:
        key: apps/{{ .Values.appName }}/oidc
        property: client-secret
    - secretKey: issuer-url
      remoteRef:
        key: apps/{{ .Values.appName }}/oidc
        property: issuer-url
{{- end }}
